services:
  hyperf-app:
    container_name: hyperf-app
    image: hyperf-app
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    entrypoint: ['php', '/opt/www/bin/hyperf.php', 'server:watch']
    depends_on:
      - mysql
    networks:
      - hyperf-network

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: 'Asia/Tokyo'
    volumes:
      - './mysql:/var/lib/mysql'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
      retries: 3
      timeout: 5s
    networks:
      - hyperf-network

  composer:
    image: composer:2.6.5
    volumes:
      - .:/var/www/html
    environment:
      - PHP_VERSION=8.3
    working_dir: /var/www/html

networks:
  hyperf-network:
    driver: bridge
